version: "3.7"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1324"
      MYSQL_DATABASE: test
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
